[package]
name = "kyros"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
# wasm-bindgen = "0.2.87"
hsv = "0.1.1"
image = "0.24.6"
time = "0.3.22"
base64 = "0.21.4"
csscolorparser = "0.6.2"

# [lib]
# crate-type=["cdylib"]
